# Generated by Django 6.0.3 on 2026-03-25 04:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_entrada', models.DateField(default=django.utils.timezone.now)),
                ('idade', models.IntegerField(blank=True, null=True)),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('F', 'Fêmea')], max_length=1)),
                ('cor', models.CharField(blank=True, max_length=50, null=True)),
                ('descricao', models.TextField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('adotado', 'Adotado'), ('em_tratamento', 'Em Tratamento')], default='disponivel', max_length=20)),
                ('usuario_cadastro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pets_cadastrados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
