# Generated by Django 6.0.3 on 2026-05-03 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adotante',
            fields=[
                ('cpf', models.CharField(help_text='Formato: 000.000.000-00', max_length=14, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('endereco', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Adotante',
                'verbose_name_plural': 'Adotantes',
            },
        ),
    ]
