# Generated by Django 6.0.3 on 2026-05-03 23:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatos', '0002_adotante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_adocao', models.DateField(default=django.utils.timezone.now)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('adotante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets_adotados', to='gatos.adotante')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adocoes', to='gatos.pet')),
            ],
            options={
                'verbose_name': 'Adoção',
                'verbose_name_plural': 'Adoções',
            },
        ),
    ]
