# Generated by Django 6.0.3 on 2026-05-04 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatos', '0003_adocao'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_pets/'),
        ),
        migrations.AlterField(
            model_name='adotante',
            name='cpf',
            field=models.CharField(help_text='000.000.000-00', max_length=14, primary_key=True, serialize=False),
        ),
    ]
