# Generated by Django 6.0.3 on 2026-05-04 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gatos', '0004_pet_foto_alter_adotante_cpf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='nome',
        ),
    ]
