# Generated by Django 6.0.3 on 2026-05-04 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatos', '0005_remove_pet_foto_remove_pet_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_pets/'),
        ),
    ]
