# Generated by Django 6.0.3 on 2026-05-19 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatos', '0006_pet_foto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pet',
            options={'verbose_name': 'Pet', 'verbose_name_plural': 'Pets'},
        ),
        migrations.AddField(
            model_name='pet',
            name='nome',
            field=models.CharField(default='Sem nome', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adocao',
            name='adotante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adocoes', to='gatos.adotante'),
        ),
        migrations.AlterField(
            model_name='adocao',
            name='pet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adocao', to='gatos.pet'),
        ),
    ]
