# Generated by Django 6.0.3 on 2026-05-19 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatos', '0007_alter_pet_options_pet_nome_alter_adocao_adotante_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='foto',
        ),
        migrations.AddField(
            model_name='pet',
            name='foto_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
